import { defineCollection, z } from 'astro:content'
import { glob } from 'astro/loaders'

// Pages: static site pages. `order` controls nav position; `description` is
// used for the meta description / link previews (falls back to site default).
const pages = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/pages' }),
  schema: z.object({
    title: z.string(),
    order: z.number().optional(),
    description: z.string().optional(),
  }),
})

// Posts: dated writing, listed newest first at /posts. Every field is
// optional; src/lib/posts.ts fills in the defaults (title from a leading "# "
// line, date from the file name, and so on) and finds a post's recording.
const postSchema = z.object({
  title: z.string().optional(),
  date: z.coerce.date().optional(),
  summary: z.string().optional(),
  authors: z.array(z.string()).optional(),
  // Whether the post is a candidate for the home page list (default true).
  // The home page shows the most recent few candidates (see
  // components/RecentPosts.astro); every post is listed at /posts.
  featured: z.boolean().optional(),
  // Where the post first appeared, if it is a repost.
  originalUrl: z.string().url().optional(),
  // Shows the "Written by Humans, Not by AI" badge (notbyai.fyi). Defaults
  // to true for a post with a recording.
  writtenByHuman: z.boolean().optional(),
  // Shows the invitation to watch the replay as a large card instead of a
  // quiet line under the byline.
  replayProminent: z.boolean().optional(),
  // URLs to feature as auto-captured screenshot cards at the end of the post.
  // Shots are generated by scripts/generate-thumbnails.mjs into
  // src/assets/thumbnails/ (run `npm run thumbnails`).
  thumbnails: z.array(z.string().url()).optional(),
  // ES modules that define the web components the post uses, loaded on its
  // page. Published posts may only use libraries uploaded with `npm run lib`
  // (see src/lib/posts.ts and the README, "Widget libraries").
  scripts: z.array(z.string().url()).optional(),
})

const posts = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/posts' }),
  schema: postSchema,
})

// Drafts: undated posts, src/content/draft_posts/<slug>.md, shown only at
// /drafts/<slug>/ (listed at /drafts/, which nothing links to).
const draft_posts = defineCollection({
  loader: glob({ pattern: '**/*.{md,mdx}', base: './src/content/draft_posts' }),
  schema: postSchema,
})

export const collections = { pages, posts, draft_posts }
